# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_auto_20160413_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
